### ISSUE TITLE
Schema enforcer plugin failure

### ISSUE THREAD

**Issue by prk2331** [PostHog/posthog-schema-enforcer-plugin#4]
Hi team, I cheked Schema enforcer plugin on posthog cloud version as well as posthog on-premise version, in both version
Im getting the below error in my logs:
Please guide

Timestamp
Source
Type
Message
2023-05-22 12:52:46.413 UTC	PLUGIN	ERROR	Error: /index.ts: Cannot import './lib'! This package is not provided by PostHog in plugins.
    at PluginPass.exit (/code/plugin-server/dist/worker/vm/transforms/replace-imports.js:12:27)
    at newFn (/code/plugin-server/node_modules/.pnpm/@babel+standalone@7.21.4/node_modules/@babel/standalone/babel.js:14108:23)
    at NodePath._call (/code/plugin-server/node_modules/.pnpm/@babel+standalone@7.21.4/node_modules/@babel/standalone/babel.js:46683:20)
    at NodePath.call (/code/plugin-server/node_modules/.pnpm/@babel+standalone@7.21.4/node_modules/@babel/standalone/babel.js:46672:19)
    at NodePath.visit$1 [as visit] (/code/plugin-server/node_modules/.pnpm/@babel+standalone@7.21.4/node_modules/@babel/standalone/babel.js:46726:10)
    at TraversalContext.visitQueue (/code/plugin-server/node_modules/.pnpm/@babel+standalone@7.21.4/node_modules/@babel/standalone/babel.js:48163:18)
    at TraversalContext.visitMultiple (/code/plugin-server/node_modules/.pnpm/@babel+standalone@7.21.4/node_modules/@babel/standalone/babel.js:48139:19)
    at TraversalContext.visit (/code/plugin-server/node_modules/.pnpm/@babel+standalone@7.21.4/node_modules/@babel/standalone/babel.js:48185:21)
    at traverseNode (/code/plugin-server/node_modules/.pnpm/@babel+standalone@7.21.4/node_modules/@babel/standalone/babel.js:48201:19)
    at NodePath.visit$1 [as visit] (/code/plugin-server/node_modules/.pnpm/@babel+standalone@7.21.4/node_modules/@babel/standalone/babel.js:46724:23)
    at TraversalContext.visitQueue (/code/plugin-server/node_modules/.pnpm/@babel+standalone@7.21.4/node_modules/@babel/standalone/babel.js:48163:18)
    at TraversalContext.visitSingle (/code/plugin-server/node_modules/.pnpm/@babel+standalone@7.21.4/node_modules/@babel/standalone/babel.js:48143:21)
    at TraversalContext.v
```![Schema

**Comment by prk2331** [comment]
@yakkomajuri sorry to tag you here directly
But im stuck in this from a long
Can you please guide in this issue

below is my json, which i tried to upload.
posthog.capture("add-to-cart", {"quantity": "2"})

```
{
    "onlyIngestEventsFromFile": false,
    "eventSchemas": {
        "add-to-cart": {
            "acceptOnlySchemaProps": true,
            "schema": {
                "product_id": {
                    "type": "string",
                    "required": true
                },
                "quantity": {
                    "type": "string",
                    "required": false
                }
            }
        }
    }
}
```
